# Generated by Django 3.0.7 on 2020-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sender_email',
            field=models.EmailField(default='EMPTY_EMAIL', max_length=254),
        ),
    ]
