# Generated by Django 3.0.7 on 2020-07-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(unique=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('publisher', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('page_count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'volumes',
            },
        ),
    ]
