# Generated by Django 3.0.7 on 2020-07-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_email_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='received_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
