# Generated by Django 3.0.7 on 2020-07-05 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('highlights', '0003_highlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['received_at'], 'verbose_name_plural': 'emails'},
        ),
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['location'], 'verbose_name_plural': 'highlights'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'volumes'},
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highlights.Volume')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='highlight',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='highlights.Entry'),
            preserve_default=False,
        ),
    ]
