# Generated by Django 3.0.7 on 2020-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0004_auto_20200705_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
